# Generated by Django 5.1.5 on 2025-03-29 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_batch_enrollment_school_delete_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='class_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='batch',
            name='name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
