# Generated by Django 5.1.5 on 2025-03-29 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_batch_options_remove_customuser_resume_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='code',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
