# Generated by Django 5.1.5 on 2025-03-29 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_school_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='name',
        ),
    ]
