# Generated by Django 5.1.5 on 2025-03-29 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_school_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batch',
            options={},
        ),
    ]
